name: Build
on: push
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3.0.2

      - name: Dependencies
        run: |
          make dependencies

      - name: Lint
        run: |
          make lint
          
      - name: Test
        run: |
          make test
