name: Build
on: push
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20.4

      - name: Check out source code
        uses: actions/checkout@v3.5.2

      - name: Dependencies
        run: |
          make dependencies

      - name: Lint
        run: |
          make lint
          
      - name: Test
        run: |
          make test
