name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Dependencies
        run: |
          make dependencies

      - name: Lint
        run: |
          make lint
          
      - name: Test
        run: |
          make test